name: goreleaser

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  ci:
    uses: rancher/webhook/.github/workflows/ci.yaml@release/v0.5
    permissions:
      contents: read
  goreleaser:
    needs: [
      ci
    ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: Package release helm charts
        run: make package-helm
      - run: mkdir -p ./build/artifacts/ && mv -v ./dist/artifacts/ ./build/
      - uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
